# https://puppet.com/misc/puppet-enterprise-lifecycle
# https://puppet.com/docs/pe/2018.1/overview/getting_support_for_pe.html
# ------------------------------------------------------------------------------
# Release       Puppet   Ruby   EOL
# PE 2016.4.15  4.10.12  2.1.9  2018-12 (LTS)
# SIMP 6.0      4.8.2    2.1.9  TBD
# SIMP 6.1      4.10.6   2.1.9  TBD
# SIMP 6.2      4.10.12  2.1.9  TBD
# SIMP 6.3      5.5.7    2.4.4  TBD***
# PE 2018.1     5.5.6    2.4.4  2020-05 (LTS)***
#
# *** = Modules created for SIMP 6.3+ are not required to support Puppet < 5.5
---
language: ruby
cache: bundler
sudo: false

bundler_args: --without development system_tests --path .vendor

notifications:
  email: false

addons:
  apt:
    packages:
      - rpm

before_install:
  - rm -f Gemfile.lock
  - gem update --system

jobs:
  include:
    - stage: check
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 5.5"
      script:
        - bundle exec rake pkg:compare_latest_tag
        - bundle exec rake pkg:create_tag_changelog

    - stage: spec
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 5.5.6"
      script:
        - bundle exec rake spec

    - stage: spec
      rvm: 2.4.4
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 5.5"
      script:
        - bundle exec rake spec

    - stage: spec
      rvm: 2.1.9
      env: STRICT_VARIABLES=yes PUPPET_VERSION="~> 4.10.4"
      script:
        - bundle exec rake spec

    - stage: deploy
      rvm: 2.4.4
      if: 'fork = false AND tag = true'
      script:
        - true
      before_deploy:
        - "export SPECFILE_VERSION=`rpm -q --specfile build/*.spec --queryformat '%{VERSION}'`"
        - '[[ $TRAVIS_TAG =~ ^${SPECFILE_VERSION}$ ]]'
      deploy:
        - provider: releases
          api_key:
              secure:  "nu21GrVv32ROPxcVT/98WCfC+wPye7he0QbEHCl/YaMP8/uDpz1hm8l/HaEox++cWNsA+gxBNsuFEWoCOo4XUb/OGmpK9440wTIxtkzbdd1+D1ZCBMdrzRLd+PGyGdYaMOizuNfaKKNxOeHdaIHeJ63zTTbKk/aOkEio5f3slryNigNeoVo+JDhjzQfLIPIK2ocKPos8sEwItIJaXZCwbCqxLrtug1ORITORrjvjcOVXaY7RMqxnyN4u6wNhsfR39kNBR+DGbtrsw8M4Y70D3cQb3d13LcbP4aYn7LH2VU6POJB3k5kl3zQBy4405XrKvFX1dfaT3kY7ALthdNY1vwefKIWsWwQn2RNsK4g3nWNrUFfEbt4cmxMRda1LWk4xGEIOZi/8iPFXrqq9yiqI6h0dMma/HJ0HG5gbGR4ucXwhW6fLoRV5seDk7i7rqFPnrufm/Bk6I5xuvYderfQLh8BPdtQGV9t8nHHGSi/hZCtTi47uy6vin/6k4x29l3ZrbEfbr3DmiksDP5T7eQp1OuGLRSCAUkDrixXCfuz/EfAr1MsnxYrCzaHTkfhBpFNAbvoSDM9j42/DKaj/6JgzS+1ndzpSZspYpuMapqvRQY/ykXEwi0IC5v9+UwUwb85+yNCoowI9I0EL+Gy4Z8gcv58MV98tTsd0ni8ldUOJycc="
          skip_cleanup: true
          on:
            tags: true
            condition: '($SKIP_PUBLISH != true)'
