---
language: ruby
sudo: false
cache: bundler
before_script:
- bundle update
bundler_args: "--without system_tests"
before_install: rm Gemfile.lock || true
script:
  - bundle exec rake spec
notifications:
  email: false
rvm:
  - 1.8.7 # CentOS 6
  - 1.9.3 # CentOS 7
  - 2.0.0
  - 2.1.9 # Current Puppet AIO version
  - 2.4.1 # Future Puppet AIO version
matrix:
  fast_finish: true
